### PR TITLE
Predictions of weak learners

### PR DESCRIPTION
**Pull request by pmneila**
New method `wlpredictWithChannels` for getting the predictions of every weak learner. The method `wl_alphas` returns the weights of the weak learners. Therefore, the final boosting scores could be obtained with

```python
wlpred = model.wlpredictWithChannels(image, eig, channels, anisotropy)
alphas = model.wl_alphas()
pred = np.tensordot(wlpred, alphas, (0,0)) 
```

`pred` should be equal (up to numerical precision) to the output of `predictWithChannels`:

```python
pred2 = model.predictWithChannels(image, eig, channels, anisotropy)
print np.allclose(pred, pred2) # Should be True
```

### CODE REVIEW

**Comment by cbecker** [comment]
Hi Pablo, as I expected we now have conflicts with this PR, after merging the PR from Stuart.
If you have some time and you can do a new one let me know, then we can merge it.

**Comment by pmneila** [comment]
I think it is fixed now.

**Comment by cbecker** [comment]
great.

one more thing, which I think would clarify what the function does.
Can we change the name to `predictIndividualWeakLearners()` or something like that, because `wlpredict()` is sort of ambiguous. 

(apologies for being pedantic here)

**Comment by pmneila** [comment]
Absolutely. But then we might have to remove the `WithChannels` part out of the name or the final name would be `wlpredictIndividualWeakLearnersWithChannels`, which is not very convenient. 

On the other hand, related to naming conventions, should `wl_alphas` be renamed to `wlalphas` or `wlAlphas` or similar?

**Comment by cbecker** [comment]
For now we should keep the `WithChannels()`, so that then when we remove them we can do it for all of them. This is an 'artifact' from a previous PR.

For C++ code I use `wlAlphas` or `mWLAlphas`, but for python you can use what fits the rest of the code, I don't think it matters too much here.

**Comment by pmneila** [comment]
Renamed everything to match the naming conventions of existing methods. Also renamed all wlpredict* to predictIndividualWeakLearners*.

**Comment by cbecker** [comment]
Thanks, that's great!!

**Pull request merged**
